Test-Skill_UI/Models/DataModel.cs
namespace Test_Skill_UI.Models
{
    public class DataModel
    {
        public string Value { get; set; }
        public string Result { get; set; }
    }
}

Test-Skill_UI/Models/ErrorViewModel.cs
namespace Test_Skill_UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Test-Skill_UI/Models/RequestAnswer.cs
namespace Test_Skill_UI.Models
{
    public class RequestAnswer<T>
    {
        public string ErrorContent { get; set; }
        public T Result { get; set; }

    }
}

Test-Skill_UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Test_Skill_UI.Extension;
using Test_Skill_UI.Models;
using Test_Skill_UI.Other;

namespace Test_Skill_UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return View();

            value = value.ClearDoubleSpace();

            var numArr = value.Split(' ').Where(x => int.TryParse(x,out int b)).Select(x => int.Parse(x));

            var responce = await Server.SendRequest<int>(new { numbers = numArr }, @"http://localhost:5144/api/sum");

            if(responce.ErrorContent!= null)
                return View(new DataModel() { Result = responce.ErrorContent });

            return View(new DataModel() { Result = responce.Result.ToString()});
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Test-Skill_UI/Controllers/PalindromeController.cs
using Microsoft.AspNetCore.Mvc;
using Test_Skill_UI.Models;
using Test_Skill_UI.Other;

namespace Test_Skill_UI.Controllers
{
    public class PalindromeController : Controller
    {
        public IActionResult Palindrome()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Palindrome(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return View();

            var responce = await Server.SendRequest<bool>(value.Trim(), @"http://localhost:5144/api/palindrome?value=" + value.Trim());

            if (responce.ErrorContent != null)
                return View(new DataModel() { Result = responce.ErrorContent });

            return View(new DataModel() { Result = responce.Result ? "Да" : "Нет" });
        }
    }
}

Test-Skill_UI/Controllers/SortController.cs
using Microsoft.AspNetCore.Mvc;
using Test_Skill_UI.Extension;
using Test_Skill_UI.Models;
using Test_Skill_UI.Other;

namespace Test_Skill_UI.Controllers
{
    public class SortController : Controller
    {
        public IActionResult Sort()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Sort(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
                return View();

            value = value.ClearDoubleSpace();

            var numArr = value.Split(' ').Where(x => int.TryParse(x, out int b)).Select(x => int.Parse(x));

            var responce = await Server.SendRequest<IEnumerable<int>>(new { numbers = numArr }, @"http://localhost:5144/api/sort");

            if (responce.ErrorContent != null)
                return View(new DataModel() { Result = responce.ErrorContent });

            return View(new DataModel() { Result = string.Join(" ", responce.Result) });
        }
    }
}

Test-Skill_UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model DataModel

<div class="text-center">
    <h1 class="display-4">Сложение отрицательных чисел</h1>
    <h2 class="display-3">Введите числа через пробел</h2>
    <h2 class="display-2">Результат:</h2>
    <h3 class="display-1">
        @{
            if (Model != null)
            {
                @Model.Result
                ;
            }
        }
    </h3>
    <form asp-controller="Home" method="post">
        <div>
            <input asp-for="Value" type="text" />
        </div>
        
        <input class="btn btn-outline-primary" value="Получить сумму" type="submit"/>
    </form>
</div>

Test-Skill_UI/Views/Palindrome/Palindrome.cshtml
@{
    ViewData["Title"] = "Palindrome Page";
}
@model DataModel

<div class="text-center">
    <h1 class="display-4">Палиндром</h1>
    <h2 class="display-3">Введите предложение</h2>
    <h2 class="display-2">Результат:</h2>
    <h3 class="display-1">
        @{
            if (Model != null)
            {
                @Model.Result
                ;
            }
        }
    </h3>
    <form asp-controller="Palindrome" method="post">
        <div>
            <input asp-for="Value" type="text" />
        </div>

        <input class="btn btn-outline-primary" value="Сортировать" type="submit" />
    </form>
</div>

Test-Skill_UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Test_Skill_UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Test_Skill_UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Test_Skill_UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Сумма</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Palindrome" asp-action="Palindrome">Палиндром</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sort" asp-action="Sort">Сортировка</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Test-Skill_UI/Views/Sort/Sort.cshtml
@{
    ViewData["Title"] = "Sort Page";
}
@model DataModel

<div class="text-center">
    <h1 class="display-4">Сортировка</h1>
    <h2 class="display-3">Введите числа через пробел</h2>
    <h2 class="display-2">Результат:</h2>
    <h3 class="display-1">
        @{
            if (Model != null)
            {
                @Model.Result
                ;
            }
        }
    </h3>
    <form asp-controller="Sort" method="post">
        <div>
            <input asp-for="Value" type="text" />
        </div>

        <input class="btn btn-outline-primary" value="Сортировать" type="submit" />
    </form>
</div>